# Generated by automated fix on 2025-09-05
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_startupsform_businessplanfile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=500)),
                ('lastName', models.CharField(blank=True, max_length=500)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('birthDate', models.DateField(blank=True)),
                ('countryOfResidence', models.CharField(blank=True, max_length=500)),
                ('provinceOfResidence', models.CharField(blank=True, max_length=500)),
                ('preferredAreas', models.CharField(blank=True, max_length=500)),
                ('howDidYouKnowUs', models.CharField(blank=True, max_length=500)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
