version: '3.9'

services:
  web:
    container_name: nova-api
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/bin/sh", "-c", "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"]
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    # depends_on:
    #   - db
    env_file:
      - .env
      
#   db:
#     container_name: novanest-db
#     image: mysql:8.0
#     restart: always
#     environment:
#       MYSQL_DATABASE: novanest_db
#       MYSQL_USER: novanest_user
#       MYSQL_PASSWORD: securepassword
#       MYSQL_ROOT_PASSWORD: rootpassword
#     ports:
#       - "3306:3306"
#     volumes:
#       - db_data:/var/lib/mysql

# volumes:
#   db_data:
