version: '3.9'

services:
  web:
    container_name: novanest-api
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DEBUG=True
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - DB_NAME=novanest_db
      - DB_USER=novanest_user
      - DB_PASSWORD=securepassword
      - DB_HOST=db
      - DB_PORT=3306

  db:
    container_name: novanest-db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: novanest_db
      MYSQL_USER: novanest_user
      MYSQL_PASSWORD: securepassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
